labels:
  - name: invalid
    labeled:
      issue:
        body: Please follow the issue templates and contributing guidelines.
        action: close
      pr:
        body: Thank you @{{ pull_request.user.login }} for suggesting this. Please follow the pull request templates.
        action: close
    unlabeled: 
      issue:
        action: open
  - name: wontfix
    labeled:
      issue:
        body: This will not be worked on, but I appreciate your contribution.
        action: close
    unlabeled:
      issue:
        action: open
  - name: duplicate
    labeled:
      issue:
        body: This issue already exists.
        action: close
    unlabeled:
      issue:
        action: open
