blank_issues_enabled: false
contact_links:
  - name: Questions about filer list in [`other lists`](https://github.com/JohnyP36/Personal-List/tree/main/other%20lists)
    url: https://github.com/JohnyP36/Personal-List/discussions/new
    about: Answers to questions and other kinds of help support is provided on the Discussions tab of this repository
