blank_issues_enabled: false
contact_links:
  - name: Questions about filer list in the "other lists" folder
    url: https://github.com/JohnyP36/Personal-List/discussions/new?category=filter-rules
    about: Answers to questions and other kinds of help support is provided on the Discussions tab of this repository
