name: EasyList Dutch
description: Use this template for issues regarding `EasyList Duth` filters
body:
  - type: markdown
    attributes:
      value: | 
        Any additions, changes or removals is at the Authors discretion. 
        You're free to counterargue (to a certain point) if you disagree with the decision. 
        To avoid being banned, don't constantly re-open or create new (related) issue reports.

  - type: checkboxes
    attributes:
      label: Prerequisites
      description: Check the appropriate boxes before you submit your issue.
      options:
        - label: This is a **Dutch** domain, so no general websites with Dutch subdomains (e.g. nl.y8.com)
          id: name11
          required: true
        - label: I performed a [cursory search of the issue tracker](https://github.com/JohnyP36/Personal-List/issues) to avoid opening a duplicate issue
          id: name12
          required: true
        - label: I tried to reproduce the issue when...
          id:name13
          required: true
  - type: checkboxes
    attributes:
      label: " "
      id: name21
      options:
        - label: I have/had [EasyList](https://easylist.to/easylist/easylist.txt) and [EasyPrivacy](https://easylist.to/easylist/easyprivacy.txt) enabled
          id: name22
          required: true
        - label: Other privacy related webextensions are disabled
          description: This is to ensure there are no issues or conflicts with other webbrowser extensions
          id: name23
          required: true
        - label: I am running the latest version of uBlock Origin (or Adguard or Adblock Plus, etc.)
          id: name24
          required: false
        - label: This is not an `NSFW` issue
          description: If it is an "NSFW" issue use this [issue template]()
          id: name25
          required: true
          
  - type: textarea
    attributes:
      label: URL(s) where the issue occurs
      description: At least one URL for a web page where the clearly described issue occurs is **mandatory**. 
        The backticks (`) surrounding the URLs are important, it prevents the URL from being clickable.
      id: name3
      placeholder: |
        `example.nl`
        `xyz.example.nl`
        `example.com/abc`
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe the issue
      description: Be as clear as possible. Nobody can read mind, and nobody is looking at your issue over your shoulder.
      id: name4
      placeholder: Just a description of the issue when you visit the site. Or steps on reproducing this.
    validations: 
      required: true

  - type: textarea
    attributes: 
      label: Screenshot(s)
      description: Screenshot(s) for difficult to describe visual issues are **mandatory**.
    validations: 
      required: false

  - type: dropdown
    attributes: 
      label: Browser + Extension **name**
      description: Browser
      id: name61
      multiple: true
      options: 
        - Microsoft Edge
        - Chrome
        - Firefox
        - Safari
        - Brave
        - another browser
    validations:
      required: true
  - type: dropdown
    attributes:
      label: " "
      description: Extension name
      id: name62
      multiple: true
      options: 
        - uBlock
        - Adguard
        - AdBlock (Plus)
        - another adblocker
    validations: 
      required: true
  - type: input
    attributes: 
      label: Browser + Extension **version**
      description: Browser
      id: name63
  - type: input
    attributes:
      label: " "
      description: Extension
      id: name64

  - type: textarea
    attributes: 
      label: Notes
      description: | 
        Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. 
        This is especially true for issues arising from settings which are very different from default ones. 
        If you suspect certain filters mention it below (this helps spending time to debug it manually).
      placeholder: Write here the result of whatever investigation work you have done
    validations: 
      required: false
