name: Deploy to gh-pages branch

on:
  push:
    branches:
      - main
    paths:
      - 'easylistdutch/**'
      - 'Personal%20List%20(uBo).txt'
  workflow_dispatch:

# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    name: Publish lists
    runs-on: ubuntu-latest
    steps:
      - name: Clone easylistdutch
        uses: actions/checkout@v3
        with:
            ref: gh-pages
      - name: Copy filter lists to gh-pages
        run: |
             TMPFILE=$(mktemp -d)
             git clone --depth=1 https://github.com/Personal-List/Personal%20List%20(uBo).git $TMPFILE
             cp $TMPFILE/Personal%20List%20(uBo).txt Personal%20List%20(uBo).txt
      - name: Patch last-updated field
        run: |
          DATE=$(date -Ru)
          for f in $(git diff --name-only); do
            STAT=$(git diff --numstat $f | sed -r '/^1\s+1\s+/d')
            if [[ -n $STAT ]]; then
              sed -ir "0,/^! Last modified: /s/^\(! Last updated: \)%timestamp%/\\1$DATE/" $f
            else
              git checkout -q $f
            fi
          done
      - name: Commit changes (if any)
        run: |
          if [[ -n $(git diff) ]]; then
            git config user.name "GitHub-Actions"
            git config user.email "<>"
            git add -u Personal%20List%20(uBo).txt
            git commit -m "Update modified filter lists"
            git push origin gh-pages
          fi
